name: camarra_clean
description: A new Flutter project for Camarra

publish_to: "none" # tento projekt nebude publikovaný na pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0

  # UI & UX
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
