// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOucxvlyYrAzYu3EZnW-zyx-6z0t3Tnc',
    appId: '1:967264804298:web:6126584bb76e7af4fdc333',
    messagingSenderId: '967264804298',
    projectId: 'camarra-1-0',
    authDomain: 'camarra-1-0.firebaseapp.com',
    storageBucket: 'camarra-1-0.firebasestorage.app',
    measurementId: 'G-FV22XWY4RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkJQMWL8y1BiK-02qE_ozfRy0hgJjwI3M',
    appId: '1:967264804298:android:e4e04cfe9b100512fdc333',
    messagingSenderId: '967264804298',
    projectId: 'camarra-1-0',
    storageBucket: 'camarra-1-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2nfRjseYZda5j7XOOiLR4ZzvM27vQiqY',
    appId: '1:967264804298:ios:0ddc2e16a21424d9fdc333',
    messagingSenderId: '967264804298',
    projectId: 'camarra-1-0',
    storageBucket: 'camarra-1-0.firebasestorage.app',
    iosBundleId: 'com.example.camarra10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2nfRjseYZda5j7XOOiLR4ZzvM27vQiqY',
    appId: '1:967264804298:ios:0ddc2e16a21424d9fdc333',
    messagingSenderId: '967264804298',
    projectId: 'camarra-1-0',
    storageBucket: 'camarra-1-0.firebasestorage.app',
    iosBundleId: 'com.example.camarra10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnOucxvlyYrAzYu3EZnW-zyx-6z0t3Tnc',
    appId: '1:967264804298:web:7523d7bc5b2de369fdc333',
    messagingSenderId: '967264804298',
    projectId: 'camarra-1-0',
    authDomain: 'camarra-1-0.firebaseapp.com',
    storageBucket: 'camarra-1-0.firebasestorage.app',
    measurementId: 'G-XZSN4LLC7W',
  );
}
